### ISSUE TITLE
Перечень задач

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#1]
Разработка интерфейса программы @Llouqs 
Разработка логики программы @DanilKozlov00  @Dudka567 
Разработка тестов для программы @Silumgaaar

**Comment by shatrovaoa** [comment]
Вы не совсем правильно поняли. То, что вы прописали списком, во-первых, не несет никакой конкретики, во-вторых, подобные элементы списка и будут являться задачами, но только доведенными до ума. Не стоит закидывать их в единую задачу "Перечень задач".

**Comment by YuriSilenok** [comment]
Подтверждаю

> Вы не совсем правильно поняли. То, что вы прописали списком, во-первых, не несет никакой конкретики, во-вторых, подобные элементы списка и будут являться задачами сами по себе, но только доведенными до ума. Не стоит закидывать их в единую задачу "Перечень задач".
