### ISSUE TITLE
Разработать ТЗ к схеме на логических элементах

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#104]

**Comment by Dudka567** [comment]
[Техническое задание](https://docs.google.com/document/d/1KVFFrJFAX1H9qSkYsZoLANhz_-pEQXI9/edit)

**Comment by Dudka567** [comment]
Здравствуйте.
Я исправил.

**Comment by Dudka567** [comment]
Здравствуйте.
Еще раз исправил.

**Comment by shatrovaoa** [comment]
Добрый день.

Теперь правильно.
