### ISSUE TITLE
Разработать руководство пользователя для схемы на логических элементах

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#105]

**Comment by Dudka567** [comment]
[Руководство пользователя](https://docs.google.com/document/d/1x4BagiE_7ozLufv2dGTaFjONK57c8Jso/edit)

**Comment by shatrovaoa** [comment]
Добрый день.

Суть у Вас правильная, а вот представлена она вряд ли как для пользователей. Посмотрите [пример](https://helpcenter.r7-office.ru/pdf/Guides/desktop_documenteditor.pdf) и добавьте наглядности.

**Comment by Dudka567** [comment]
Здравствуйте.
Я исправил.

**Comment by shatrovaoa** [comment]
Добрый день.

Теперь правильно.
