### ISSUE TITLE
Разработать диаграмму классов для графического инструмента

### ISSUE THREAD

**Issue by Tyson44-rus** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#111]

**Comment by JackiEwens** [comment]
[диаграмма классов](https://drive.google.com/file/d/16o4ROZ6Q772n5GTlGjKIoTvkpwSqjUr-/view?usp=sharing)

**Comment by JackiEwens** [comment]
[Пояснительная записка к диаграмме классов](https://docs.google.com/document/d/1FCQ55e8pjmc-eMSuNRJul1WHBJd6OzP8XvKRlGvdigM/edit?usp=sharing)

**Comment by shatrovaoa** [comment]
Добрый день.

Скорректируйте несколько моментов:
— По описанию класс Saved предназначен для хранения элементов, значит между Form1 и Saved должна быть ассоциация, а не композиция.
— Классы компонентов должны быть связаны не с Form1, а с Saved композицией.

**Comment by JackiEwens** [comment]
Здравствуйте.

Всё исправлено.

**Comment by shatrovaoa** [comment]
Добрый день.

Теперь порядок.
