### ISSUE TITLE
Разработать ТЗ

### ISSUE THREAD

**Issue by JackiEwens** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#112]

**Comment by JackiEwens** [comment]
[Техническое задание](https://docs.google.com/document/d/1RYpfjtyqm0BTLwVrNeE-ELpVHeuM52S9klnXv_BxvJA/edit?usp=sharing)

**Comment by shatrovaoa** [comment]
Добрый день.

Несколько корректировок:
— В ТЗ Вы пишете, что Вам нужно не менее 4-х человек, но Вас работает двое;
— Название вашего приложения должно включать "Диаграмма деятельности", т.е. соответствовать теме курсовой работы, а не просто "Графический инструмент".

**Comment by JackiEwens** [comment]
Здравствуйте.

Всё исправлено.

**Comment by shatrovaoa** [comment]
Добрый день.

Теперь порядок.
