### ISSUE TITLE
Разработать UseCase диаграмму для графического инструмента построения диаграммы деятельности

### ISSUE THREAD

**Issue by Tyson44-rus** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#113]

**Comment by JackiEwens** [comment]
[Use case](https://drive.google.com/file/d/1Oyc_0JsU3hdFbHUdx95bqhPve_vxgh4C/view?usp=sharing)

**Comment by JackiEwens** [comment]
[Пояснительная записка к Use Case диаграмме](https://docs.google.com/document/d/1xO2nAy_UC51YCBI29Yx0Qo-8VexjM1jIcYJFyM-CMC4/edit?usp=sharing)

**Comment by shatrovaoa** [comment]
Добрый день.

Акторов на диаграмме должно быть двое: Программист-разработчик (код, интерфейсы, тестирование) и инженер-проектировщик (диаграммы, в том числе диаграмма классов и UseCase). Распишите подробнее их действия.

**Comment by JackiEwens** [comment]
Здравствуйте.

Всё исправлено. На диаграмме 3 актора, потому что наша команда состоит из 3 человек.

**Comment by shatrovaoa** [comment]
Добрый день.

Теперь порядок.
