### ISSUE TITLE
Написать руководство пользователя

### ISSUE THREAD

**Issue by JackiEwens** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#114]

**Comment by JackiEwens** [comment]
[Руководство пользователя](https://drive.google.com/file/d/1z8O52qd6jO0_z9l8AT4rC2B-uhbhi1Tn/view?usp=sharing)

**Comment by shatrovaoa** [comment]
Добрый день.

Поправьте титульный лист:
— Названия института и кафедры пишутся со слова Институт/Кафедра с большой буквы, затем название маленькими буквами, без кавычек;
— После строки о направлении подготовки с его кодом, следующей строкой пишется его название без кавычек;
— Проверьте выравнивание по центру и отсутствие лишних пробелов в заголовке самой работы, там явно виден сдвиг.

**Comment by JackiEwens** [comment]
Здравствуйте.

Всё исправлено.

**Comment by shatrovaoa** [comment]
Добрый день.

Теперь порядок.
