### ISSUE TITLE
Создание Use Сase диаграммы

### ISSUE THREAD

**Issue by leshastern** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#2]
Данная диаграмма отображает актеров и их взаимодействия с приложением "Графический интерфейс для моделирования диаграммы автомата".

**Comment by leshastern** [comment]
https://drive.google.com/open?id=1f8ooKl1WPjjH49AWy3wcTQlEMn1A8yJi

**Comment by YuriSilenok** [comment]
> https://drive.google.com/open?id=1f8ooKl1WPjjH49AWy3wcTQlEMn1A8yJi

Пожалуйста, ссылки оформляйте как ссылки, а не как URL.
Дать хоть какое-то описание этой ссылке и сообщите зачем вы дали эту ссылку в этой задаче. И заполните описание задачи, из заголовка непонятно для чего вы составляете диаграмму

**Comment by MaksimBukhanov** [comment]
Ссылка на диаграмму в Google Drive: [Use_сase](https://drive.google.com/open?id=1rulUOm4rHvj1eMrvkEglH7Z0CZwrWiiJ) диаграмма
Готовы выслушать рекомендации по ее модификации.

**Comment by None-stopCoding** [comment]
Диаграмма завершена и одобрена.
