### ISSUE TITLE
Создание диаграммы классов

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#4]
Под этой задачей будет вестись разработка диаграммы классов для  проекта.
Диаграмма: [Draw.io](https://drive.google.com/file/d/1E9wrgXZ_OSwz6DA7Eafs3BQaiNSHKNA9/view?usp=sharing)

**Comment by None-stopCoding** [comment]
Reference убран, произошла ошибка

**Comment by None-stopCoding** [comment]
Еще предстоит расписать подзадачи для этой задачи

**Comment by None-stopCoding** [comment]
Пока что диаграмма классов находится в стадии активной разработки и будет редактироваться на протяжении работы над проектом. Доступ предоставлен.

**Comment by shatrovaoa** [comment]
Добрый день.

Если Вы планируете использовать классы из Qt, я говорю конкретно про пример с QGraphicsLineItem, то он будет наследником от класса Line и стрелка будет в другую сторону. То же самое пересмотрите для других классов Qt. 

Также Вы на диаграмме не отразили связь между QGraphicsItem и QGraphicsScene.

Также если Вы решили использовать классы с привязкой к Qt, тогда пишите всю иерархию с их использованием, а не часть такая, часть такая. Я говорю, например, про наличие у Вас на диаграмме класса Line, в то время как в Qt есть класс QLineF.
