### ISSUE TITLE
Пояснительная записка к Use Case диаграмме

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/KSU.Visio.Cpp#5]
**Описание**: создание пояснительной записки к Use Case Диаграмме

**Comment by AlbertShabrov** [comment]
Ссылка на пояснительную записку к Use Case Diagram Google Drive: https://docs.google.com/document/d/1U1yBbPwPUbCyHuHiwGlVcNLyyNvx4YH4
В пояснительной записке сказано, что будет делать программа при определенных действиях пользователя.

**Comment by shatrovaoa** [comment]
Добрый день.

Я оставила комментарии в документе, внесите правки в него. И касательно ссылки на документ: оформите ее не как URL.

**Comment by None-stopCoding** [comment]
Записка завершена и одобрена.
